language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key: $HEROKU_APP_ID
  app: $HEROKU_APP_NAME
cache:
  directories:
  - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID = $MY_CC_TEST_REPORTER_ID
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT