language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key: HEROKU_APP_KEY
  app: HEROKU_APP_NAME
cache:
  directories:
  - node_modules
env:
  matrix:
  - secure: T9zp6MUXMgN9NDGxVq+9ppnGbdcW/T82ViNs0oAwYVZTp49IivDL/5RpsblOtBuNCe+p85w9AC6rpEVTTaVMGFDRcZkbtfR2hCMLQB/3XhE6IU6sDFj0iM49kjh6VVFTL0AEtNI2MvJk0z48OWIfqaSYf2/Yxk+Zb9wbjC3+36djRAnSJG6JbjTZ9iWDmX1bWzSOTIOCdFKbpcAmeNw9rCCmLmJ7q7HF+GBZcQiSn1rGXXbq3eIGksNeGbm0SHIeS5Fc+VkpAkME6T7+Hp1rhUHpghZbAD1hEpYg+7pMhKTDzy1lSRRG9gq2tkxt9Q26VZlaNcscyu/hlf4sGDb5k+QKCSAoA2KmKjDSzxMIN7tawgLwYwcVRabGlevMQ0I+chG/MnRe9XRITELdsRBcPkIi+o0ovxBBs2iQP521BivOQRx9FAJc70Pv7mza9BUAWVGvFMOWcvbcPAdpB21XZc6/6hLnJAfxKDdjVt5HqqP2MMd33lJIfwJR4RWxo0G2yfsPqfLN/iMHSkfpj0Bu8cjU6JOdjFIU2eLB/BXAaNrxKbKPvrQogXCgQaguZcaOEI3DGBtbH0UwAkN2pPMQ8Q4mQVBCMkPu189sEbCfDPQwcbT2y6C8o2EYqk8ZoltydjFSmqmsNRR62WAAEMNIlI/5KqOHEH57iDHdSizLczc=
  - secure: EznzbleZSWjNouSaot01OwhgNzbWzzGasb9xKtCU2l/d+kzR2D1NXYMXnZsm92u5UbZrKlawMHpCIaEAmttL5oQLnvoJkdyG22tcZsUv+XCZsdHP7opa4jRGrHL9iJXgB04t4t+N2e6SXalHJXPbWGr25qRC+Pexpr7gxL3L1U3j/tK657wkWxyKvPE2rgFDP5pRV2/Cyi1ZQIHLes7vsLPAQNFh/bzw6eW6anMysgQfUiLMDYvtwVrFHliQ3o6mdMDpjDCXewWDEC3TKvA989ER5jeljOclJaGmKU/qOEEnCEN7y1bWEJHWjNFarAStTmVTpi6abFNLKlzhcUjEizBe0V1KO7++j2pJ9m/IB3mRV0A5Q4kxAdHRP5qPXgr/l85TvKK+LVRBmIf2LMum4AgkE5V8X95QFXsp8MEUJp8FqJTJIvJrWRUzc94xa1st9kirPmXG0LW0Bjr/vr8UTAvXvHiLnAxIGptwVc4hWOtXkKAFE42TC+piXIPig/ApM/oYNJxdD2cl20Dh4L5DQvaGPZRw88uypR+QVmbtfgCBnFUvnXReYVBmOiA3Q+t773p/z6GbgqDuchsHUp6Omm7LWNEAdhADsju0KnM3zMhHJp6mNw8OpDVINSU80YcUukIOTK+phGW/SNPJpmzEZIjHKc+cwSVe9HrB+5cNy1Q=
